Week 1
DivoDivnoe/loftschool-burgers pull request #1
Opened 2017-07-30 22:11 UTC by DivoDivnoe

2017-07-30 22:13 UTC, DivoDivnoe reviewed
Пока не очень понял, как сделать резиновую верстку по вертикали. Кое-где применены вертикальные маржины в процентах, не уверен, что это правильно

2017-08-01 15:56 UTC, xaosaki requested changes
Шрифты потерялись http://take.ms/mInSm (скорее всего пути не те)
Центровку лучше делать через flex или через 

postion: relative;
top: 50%;
transform: translateY(-50%);

2017-08-01 15:56 UTC, xaosaki commented on index.html
> +    <div class="section-wrapper">
Это лучше сделать элементом section__wrapper

2017-08-01 15:56 UTC, xaosaki commented on index.html
> +              <a class="main-nav__link" href="#">
"а" можно в одну строчку написать, меньше места занимать будет

2017-08-01 15:56 UTC, xaosaki commented on index.html
> +        <div class="banner-item__text">
Можно сделать через блок title (на созвоне показывал)

2017-08-01 15:56 UTC, xaosaki commented on index.html
> +      <div class="promo-content">
Это блоки или элементы?

2017-08-01 15:56 UTC, xaosaki commented on index.html
> +          <div class="promo__item promo__meat">
тут лучше использовать модификатор promo__item promo__item--meat

2017-08-01 15:56 UTC, xaosaki commented on index.html
> +      <li class="reviews__item reviews__item--1">
Зачем числовые модификаторы? Картинки надо делать инлайново в html можно через background но тоже инлайново.

2017-08-01 15:56 UTC, xaosaki commented on scss/components/header.scss
> +  &__list {
лучше писать полное название (искать потом проще будет) .main-nav__list

2017-08-01 16:32 UTC, DivoDivnoe commented on index.html
> +      <li class="reviews__item reviews__item--1">
а я здесь через цикл решил вставить картинки. они у меня тоже названы review-1, review-2 и т.д. Так нельзя сделать?

2017-08-01 16:36 UTC, DivoDivnoe commented on scss/components/header.scss
> +  &__list {
то есть & вообще не использовать? или что ты имеешь в виду?

2017-08-01 16:37 UTC, xaosaki commented on index.html
> +      <li class="reviews__item reviews__item--1">
Мысль хорошая, но в данном случае это все-таки контентные картинки, которые могут наполняться из админки. И в css для бэкенда залезть будет проблематично.

2017-08-01 16:41 UTC, DivoDivnoe commented on index.html
> +      <li class="reviews__item reviews__item--1">
точно, это ж контент... переделаю

2017-08-01 17:08 UTC, DivoDivnoe commented on scss/components/header.scss
> +  &__list {
или когда мы новую вложенность создаем?

2017-08-01 17:26 UTC, xaosaki commented on scss/components/header.scss
> +  &__list {
& используем для hover, active и т. д.

2017-08-01 17:33 UTC, DivoDivnoe commented on scss/components/header.scss
> +  &__list {
понял!

2017-08-01 17:59 UTC, DivoDivnoe commented on index.html
> +        <div class="banner-item__text">
а, точно, там же заголовки одинаковые. Я тогда через примесь попробую сразу лучше

2017-08-02 17:30 UTC, merged